### PR TITLE
moved to rxJava2

### PR DESCRIPTION
**Pull request by KucherenkoIhor**

### CODE REVIEW

**Comment by oliveiradev** [comment]
Hey @KucherenkoIhor, first thanks for your contribution. What do you think about we create a new branch to maintains both versions?

**Comment by KucherenkoIhor** [comment]
@oliveiradev Hi! The first version of RxJava will not be supported in future. So I don't see any reason to use it in this library. The most amount of developers have already moved to RxJava2.

**Comment by oliveiradev** [comment]
Yeah, makes sense, the users can use previous versions to RxJava1. Can you inform this changes to README file?

**Comment by KucherenkoIhor** [comment]
@oliveiradev done

**Comment by oliveiradev** [comment]
Thank you @KucherenkoIhor!

**Pull request merged**
